#! /usr/bin/env bash

set -e

export MIX_ENV=dev
export NODE_ENV=development

# if [ ! "$(sysconfcpus --version)" ]; then
#     zip_location=~/.local/share/libsysconfcpus.zip
#     unzip_dir=~/.local/share/
#     curl -L https://github.com/obmarg/libsysconfcpus/archive/master.zip --output $zip_location
#     unzip $zip_location -d $unzip_dir
#     cd $unzip_dir/libsysconfcpus-master
#     ./configure && make && make install
# 
#     echo "sysconfcpus install complete"
# else
#     echo "sysconfcpus already installed"
# fi

mix local.rebar --force
mix local.hex --force
mix deps.get
mix compile
mix generate_schema

cd assets && npm install
cd ../

mix ellie.binstall

mix ecto.create
mix ecto.migrate
