#!/usr/bin/env bash

set -e

# Timeout after 30s if we still haven't gotten a response
timeout 30s bash <<EOT
# Wait until an HTTP request succeeds against localhost:PORT
function healthz(){
    while true; do
        if curl -sSf "http://localhost:4000/healthz" >/dev/null; then
            exit 0
        fi
    done
}

healthz
EOT
